sublime 3 command line "binaries"

diff --git a/bin/subl_wait b/bin/subl_wait
--- a/bin/subl_wait
+++ b/bin/subl_wait
@@ -6,11 +6,13 @@
 # via https://github.com/miohtama/ztanesh/blob/master/zsh-scripts/bin/subl-wrapper
 #
 
-SUBL="/Applications/Sublime Text 2.app/Contents/SharedSupport/bin/subl"
+# SUBL="/Applications/Sublime Text 2.app/Contents/SharedSupport/bin/subl"
 
-if [ ! -e "$SUBL" ] ; then
-    echo "Sublime not found: $SUBL"
-    exit 1
-fi
+# if [ ! -e "$SUBL" ] ; then
+#     echo "Sublime not found: $SUBL"
+#     exit 1
+# fi
 
-"$SUBL" --new-window -wait $@
+# "$SUBL" --new-window -wait $@
+
+subl --wait $@
