install instructions in readme

diff --git a/dot-profile b/dot-profile
--- a/dot-profile
+++ b/dot-profile
@@ -1,8 +1,21 @@
-alias editprofile='mate_wait ~/.profile;. ~/.profile'
+#
+# aliases
+#
+alias editprofile='mate_wait ~/.profile; . ~/.profile'
 alias o='open .'
 alias m='mate .'
 alias difflast='git diff HEAD^ HEAD > ~/Desktop/diff.diff'
+alias g='git'
+# Autocomplete for 'g' alias as well
+# complete -o default -o nospace -F git g
 
+# for fast multiple terminal navigation to same dir
+alias mark='pwd | pbcopy'
+alias go='cd `pbpaste`'
+alias ql='qlmanage -p 2>/dev/null' # quicklook via terminal
+
+umask 002 # prevent permissions problems
+export JOBS=4 # for faster node building
 export HISTCONTROL=ignoredups
 export HISTSIZE=10000000
 export HISTFILESIZE=10000000
@@ -10,27 +23,65 @@ export EDITOR="mate_wait"
 export VISUAL="mate_wait"
 export PAGER="less"
 export CLICOLOR="yes"
-export PROMPT_COLOR='1;1;40m';
-export PS1="\h:\W \u\$ " # default
-
+export LSCOLORS=gxBxhxDxfxhxhxhxhxcxcx
+export PROMPT_COLOR='1;1;40m'
+# default prompt
+# export PS1="\h:\W \u\$ "
 parse_git_branch() {
   git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/(\1)/'
 }
 # ~/dev/dotfiles(my-branch-name)§
 export PS1="\w\[\e[0;33;49m\]\$(parse_git_branch)\[\e[0;0m\]§ "
 
+# rm does move to trash
+# via http://blog.vicshih.com/2008/04/move-to-trash-from-mac-command-line.html
+function del() {
+  while [ -n "$1" ]; do
+    if [ ! -e "$1" ]; then
+      echo "'$1' not found; exiting"
+      return
+    fi
+
+    local file=`basename -- "$1"`
+
+    # Chop trailing '/' if there
+    file=${file%/}
+
+    local destination=''
+
+    if [ -e "$HOME/.Trash/$file" ]; then
+      # Extract file and extension
+      local ext=`expr "$file" : ".*\(\.[^\.]*\)$"`
+      local base=${file%$ext}
+
+      # Add a space between base and timestamp
+      test -n "$base" && base="$base "
+
+      destination="/$base`date +%H-%M-%S`_$RANDOM$ext"
+    fi
+
+    echo "Moving '$1' to '$HOME/.Trash$destination'"
+    \mv -i -- "$1" "$HOME/.Trash$destination" || return
+    shift
+  done
+}
+# only add to mac, in a fragile way.
+if [[ "$OSTYPE" == 'darwin10.0' ]]; then
+  alias rm='del'
+fi
+
+# Random configuration stuff
+
+# add bash completion
+if [ -f /opt/local/etc/bash_completion ]; then
+  . /opt/local/etc/bash_completion
+fi
+
+alias pr='post-review'
+alias pgstart='/opt/local/lib/postgresql84/bin/pg_ctl -D /opt/local/var/db/postgresql84/defaultdb -l logfile start'
+export MAVEN_OPTS="-server -Xms256m -Xmx512m"
+
 #
 # pull in private things or things only applicable to this machine
 #
 source ~/.private
-
-#
-# Random stuff
-#
-
-# start server
-alias pr='post-review'
-alias pgstart='/opt/local/lib/postgresql84/bin/pg_ctl -D /opt/local/var/db/postgresql84/defaultdb -l logfile start'
-
-export MAVEN_OPTS="-server -Xms256m -Xmx512m"
-
